import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterProvider from "./toastprovider/ToastProvider";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prisma Demo",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: Readonly<ReactNode>
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToasterProvider />
        {children}
        </body>
    </html>
  );
}

export default RootLayout
